# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5f14b8c881a059dba76ea040a2b3b10c2e06cb27e56f84ccd5b93e0b10361a2b75d4b90025895f8f835ff507ba0ff31f25ee16cbbbcae49820a9b7862d936b25

test:
  secret_key_base: d81f3d2c353a9ee2c40d4c79e04efda65091aeeba1b526bf98ee4c4fb82532464688132272997bb5282e78c465d2c602e69e0ab0533e7564061ce231fbb43dd9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
